# Use root/example as user/password credentials
version: '3.1'

services:
  jenkins:
    build:
      context: ./
      dockerfile: ./Dockerfile_jenkins2
    restart: always
    ports:
      - "8088:8080"
      - "50000:50000"
    expose:
      - "8080"
      - "50000"
    volumes:
      - '/jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

  mongo:
    image: mongo
    restart: always
    ports:
    - "6001:27017"
    environment:
      # MONGO_HOST: localhost
      # MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
    - "6002:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_MONGODB_AUTH_DATABASE: db
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: example
    depends_on:
      - mongo

#  nginx:
#    image: nginx
#    volumes:
#      - ./templates:/etc/nginx/templates
#    ports:
#      - "80:80"
#    environment:
#      - NGINX_HOST=napl.asuscomm.com
#      - NGINX_PORT=80