# Use root/example as user/password credentials
version: '3.1'

services:
  jenkins:
    build:
      context: ./
      dockerfile: ./Dockerfile_jenkins2
    restart: always
    ports:
      - "8088:8080"
      - "50000:50000"
    expose:
      - "8080"
      - "50000"
    volumes:
      - '/jenkins:/var/jenkins_home'
      - '/var/run/docker.sock:/var/run/docker.sock'

  mongoRs1:
    container_name: mongoRs1
    image: "mongo"
    build:
      context: ./
      dockerfile: ./Dockerfile_mongo_rs
    restart: always
    ports:
      - "6001:27017"
    expose:
      - "27017"
    volumes:
      - '/mongoRs/mongoRs1:/data/db'
    environment:
      # MONGO_HOST: localhost
      # MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: db
    command: mongod --replSet replicaSet
      networks:
      - mongo-networks

  mongoRs2:
    container_name: mongoRs2
    image: "mongo"
    restart: always
    ports:
      - "6002:27017"
    expose:
      - "27017"
    volumes:
      - '/mongoRs/mongoRs2:/data/db'
    environment:
      # MONGO_HOST: localhost
      # MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: db
    command: mongod --replSet replicaSet
      networks:
      - mongo-networks

  mongoRs3:
    container_name: mongoRs3
    image: "mongo"
    restart: always
    ports:
      - "6003:27017"
    expose:
      - "27017"
    volumes:
      - '/mongoRs/mongoRs3:/data/db'
    environment:
      # MONGO_HOST: localhost
      # MONGO_PORT: 27017
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: db
    command: mongod --replSet replicaSet
    networks:
      - mongo-networks

  mongo-express:
    image: "mongo-express"
    restart: always
    ports:
      - "8010:8081"
    environment:
#      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_SERVER: mongoRs1,mongoRs2,mongoRs3
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      # ME_CONFIG_MONGODB_AUTH_DATABASE: db
      ME_CONFIG_MONGODB_AUTH_USERNAME: root
      ME_CONFIG_MONGODB_AUTH_PASSWORD: example

    depends_on:
      - mongo_rs1

networks:
  mongo-networks:
    driver: bridge

#  nginx:
#    image: nginx
#    volumes:
#      - ./templates:/etc/nginx/templates
#    ports:
#      - "80:80"
#    environment:
#      - NGINX_HOST=napl.asuscomm.com
#      - NGINX_PORT=80